config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/thanks', to: 'welcome#thanks'
  get '/about', to: 'welcome#about'
  get '/coffee', to: 'welcome#coffee'
  get '/shop', to: 'welcome#shop'
  get '/blog', to: 'welcome#blog'
  get '/finca_jaramillo', to: 'coffees#finca_jaramillo'
  get '/finca_fernandez', to: 'coffees#finca_fernandez'
  get '/elida_estates', to: 'coffees#elida_estates'
  get 'finca_deborah', to: 'coffees#finca_deborah'
  get 'blog/panama_coffeeshops', to: 'posts#panama_coffeeshops'
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :clients
    # get "login"    => "sessions#new",         :as => "login"
    # post "logout"  => "sessions#destroy",     :as => "logout"
    # get "signup"   => "users#new",            :as => "signup"
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  enum coffee_method_used: [:espresso, :filter]
  enum coffee_grind: [:coarse, :medium, :fine]
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
  http_basic_authenticate_with :name => "panama", :password => "coffee", :only => [:index, :show]
  def index
    @clients = Client.all

    respond_to do |format|
      format.html
      format.json { render json: @clients }
    end
  end

  def new
    @client = Client.new

    respond_to do |format|
      format.html
      format.json { render json: @client }
    end
  end

  def create
    @client = Client.create(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to thanks_path, success: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @client }
    end
  end

  def edit
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @client }
    end
  end

  def update
    @client = Client.find(params[:id]) rescue nil

    unless @client
      redirect_to root_url, :error => 'You cannot update this client!'
    end

    respond_to do |format|
      if @client.update_attributes(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @client = Client.find(params[:id]) rescue nil

    unless @client
      redirect_to root_url, :error => 'You cannot delete this client!'
    end

    @client.destroy

    respond_to do |format|
      format.html { redirect_to_client_url }
      format.json { head :no_content }
    end
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :full_street_address, :email, :coffee_method_used, :coffee_grind, :coffee_selected)
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  def index
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
  end

  def sales
  end

  def visitors 
  end

  def orders
    @orders_roasted
    @orders_delivered
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all

    respond_to do |format|
      format.html
      format.json { render json: @clients }
    end
  end

  def new
    @client = Client.new

    puts @coffee

    respond_to do |format|
      format.html
      format.json { render json: @client }
    end
  end

  def create
    @client = Client.create(client_params)

    puts @coffee

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @client }
    end
  end

  def edit
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @client }
    end
  end

  def update
    @client = Client.find(params[:id]) rescue nil

    unless @client
      redirect_to root_url, :error => 'You cannot update this client!'
    end

    respond_to do |format|
      if @client.update_attributes(client_params)
        format.html { redirect_to @client, notice: 'Visitor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @client = Client.find(params[:id]) rescue nil

    unless @client
      redirect_to root_url, :error => 'You cannot delete this client!'
    end

    @client.destroy

    respond_to do |format|
      format.html { redirect_to_client_url }
      format.json { head :no_content }
    end
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :email, :full_street_address, :coffee_method_used, :coffee_ground, :coffee_selected)
  end
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  def finca_jaramillo
  end
  def finca_fernandez
  end
  def elida_estates
  end
  def finca_deborah
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def panama_coffeeshops
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def coffee
  end

  def about
  end

  def blog
  end

  def shop
  end

  def thanks
  end
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/clients/_form.html.erb
<div class="container-fluid"> 
  <div class="row-fluid">
    <div class="box">
      <div class="col-lg-12" id="new_client_form">
        <%= form_for Client.new ,url: admin_clients_path do |f| %>
          <div class="form-group">
            <%= f.label :first_name, "FIRST NAME " %>
            <%= f.text_field :first_name, :class => "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :full_street_address, "ADDRESS " %>
            <%= f.text_field :full_street_address, :class => "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :email, "EMAIL " %>
            <%= f.text_field :email, :class => "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :coffee_selected, "COFFEE SELECTION " %><br>
            <%= f.select :coffee_selected, options_for_select([["SELECT ONE", ""], "Elida Estates catuai (washed) - 250g - 18€", "Cafetalera Fernandez typica (washed) - 250g - 15€", "Elida Estates catuai (natural) - 250g - 18€", "Finca Jaramillo geisha (natural) - 150g - 21€", "Finca Deborah geisha (washed) - 150g - 30€"]), :class => 'form-control' %>
          </div>
          <%= f.submit "SEND", :class => "btn btn-primary btn-lg", :id => "btn-form" %>
        <% end %> 
      </div>
    </div>
  </div>
</div>

app/views/admin/clients/edit.html.erb
<%= render partial: "admin/clients/form" %>

app/views/admin/clients/index.html.erb
<%= link_to "Add a new Client", new_admin_client_path %>
<table class="table">
  <caption>Clients in the database.</caption>
  <thead>
    <tr>
      <th>First name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Coffee</th>
      <th>Order Date</th>
    </tr>
  </thead>
  <tbody>
  <% @clients.each do |c| %>
    <tr>
      <td><%= c.first_name %></td>
      <td><%= c.full_street_address %></td>
      <td><%= c.email %></td>
      <td><%= c.coffee_selected %></td>
      <td><%= c.created_at %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/clients/new.html.erb
<%= render partial: "admin/clients/form" %>

app/views/admin/clients/show.html.erb
<h1><%= @client.first_name %></h1>

app/views/admin/dashboard/index.html.erb
<h1>Boo!</h1>

app/views/coffees/elida_estates.html.erb
<div class="container coffee-profile-section">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <h2 class="intro-text text-center">ELIDA ESTATES</h2>
        <hr>
      </div>
      <div class="col-md-6">
        <table>
          <tr>
            <td><strong>ORIGIN</strong></td>
            <td>ALTO QUIEL, PANAMA</td>
          </tr>
          <tr>
            <td><strong>PROCESS</strong></td>
            <td>NATURAL, WASHED and HONEY</td>
          </tr>
          <tr>
            <td><strong>VARIETY</strong></td>
            <td>CATUAI and GEISHA (BRONZE/GREEN TIP)</td>
          </tr>
          <tr>
            <td><strong>PRODUCER</strong></td>
            <td>WILFORD LAMASTUS</td>
          </tr>
          <tr>
            <td><strong>ALTITUDE</strong></td>
            <td>1650+ METERS</td>
          </tr>
          <tr>
            <td><strong>NICKNAME</strong></td>
            <td>SILICON VALLEY</td>
          </tr>
        </table>
        <p><strong>THE STORY</strong></p>
        <p>The Lamastus family is a synonym of the highlands of Panama. When I was in my teens I used to go up to the Feria de Boquete, an event full of concerts and festivities that took place once a year right around the same time when the coffee harvest was at its prime. I remember very clearly partying and sharing smiles with Lamastus kids for as long as I was in Boquete around that time of the year. The family has dedicated its life and labor to coffee, which is why their harvests are as precious as gold.</p><br>
        <p>Wilford Lamastus is an inventor. Like the great Teslas, Fords and Jobs he has never sat still and just sat down to admire the 90+ coffee that his family's farms have been producing for the past 7-8 years. From washed geishas to natural catuais, Wilford and before him, his father Thatcher, have tended an Elysium in the making. Many years ago Thatcher decided to experiment with the farms grounds, which limit with one of Panama's most beautiful national parks, so he began planting specimens from peaches to tree tomatos at different altitudes. And among those dispersed seeds, those placed in the highest areas of the farm, were Geisha seeds. When he observed with others that those Geisha plants yielded green or bronze tips, they went for quality and separated and planted more green tip plants. They produced a much clearer and succulent cup of coffee.Going back to Wilford and his magic beans. He has driven the quality and the depth of his profiles to such a point that he couldn't accept the fact that only those savvy connossieurs from the West Coast and from Japan got to enjoy such wonders, so he opened the first specialty coffee shop in Panama's Old Town (and graciously called it Bajareque, after the rain that feeds the coffee fields near the volcano).</p><br>
        <p>When I first came to Elida Estates, I was at the beginning of my quest of coffee. My brother was friends with Wilford Jr, the new generation of Lamastus, and the man behind Bajareque's roasting and managing. In 2013 he arranged for me to come during the next harvest in order to learn in the farm, watch his father in action and most importantly, love it so much that when I went back to Paris I would bring some with me. He was right. His father was a mix of Indiana Jones and Steve Jobs in the sense that he would be picking cherries with the boys in the farm and driving up baristas in the worst weather conditions, but would come back religiously to cup again and again and the end of the day spend his silent moments roasting away batch after batch. A visionary. An excellent teacher. And in the end I did come back with a quintal of Elida inside 3 backpacks. Quite a story.</p>

      </div>
  
      <div class="clearfix"></div>
    </div>
  </div>
   <hr>
  <div class="row text-center">
    <div class="box">
      <div class="col-lg-12" id="call_to_action">
        <h2><a href="/shop">COME AND <strong>VISIT OUR STORE</strong>. IT'S FULL OF DELICIOUS COFFEE!</a></h2>
      </div>
    </div>
  </div>
  <hr>
</div>

app/views/coffees/finca_deborah.html.erb
<div class="container coffee-profile-section">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <h2 class="intro-text text-center">FINCA DEBORAH</h2>
        <hr>
      </div>
      <div class="col-md-6">
        <table>
          <tr>
            <td><strong>ORIGIN</strong></td>
            <td>TIERRAS ALTAS, PANAMA</td>
          </tr>
          <tr>
            <td><strong>PROCESS</strong></td>
            <td>NATURAL, WASHED and HONEY</td>
          </tr>
          <tr>
            <td><strong>VARIETY</strong></td>
            <td>GEISHA (BRONZE/GREEN TIP)</td>
          </tr>
          <tr>
            <td><strong>PRODUCER</strong></td>
            <td>JAMISON SAVAGE</td>
          </tr>
          <tr>
            <td><strong>ALTITUDE</strong></td>
            <td>1900+ METERS</td>
          </tr>
          <tr>
            <td><strong>NICKNAME</strong></td>
            <td>JURASSIC PARK</td>
          </tr>
        </table>
        <p><strong>THE STORY</strong></p>
        <p>I met Jamison in a very unusual way...the Internet. The company was being setup in Paris to source, roast and sell Panama's finest coffee in Europe. But most important over all that, I wanted to find a coffee in Panama that the world had never seen. A bit of searching led me to a very cool guy who moved from the U.S. and ended up in Boquete, land of awesome coffee. He had purchased, more than ten years ago, a lot of land that sat at a very curious location because its initial altitude began where almost every other farm on the skirts of the Baru volcano ended. Jamison turned it into his very own Jurassic Park.</p><br>
        <p>He wanted to grow the world's finest geisha. So he hired the top minds and hands in the game and he began creating what we now know as Finca Deborah, the farm growing the highest geisha in the planet. Jamison is a contrarian who has hit gold on many ventures by playing against the odds. Most people would have thought that above 1950 meters you could not grow a coffee so fine that it is called the cup of God. He proved everyone wrong. Now with geisha plants in almost optimum conditino at 4 years of growth, the are expected to yield this year or the next the world's most expensive geisha.</p><br>
        <p>Since part of the coffee ecosystem is made by the hundreds of hands that contribute to every harvest, Jamison is almost finished constructing the necessary infrastucture for Finca Deborah to be called a little village. From setting up comfortable living quarters for the workers to gardens filled with vegetables and two chicken coops, the place is worth visiting. Actually I have a very distinct memory of meeting to pickers in while trekking the farm and being astonished at the fact that they were wearing John Deere wind-breaking, impermeable, badass uniforms.</p><br>
        <p>Finca Deborah upholds every value that we work with, from innovation to sustainable impact to niche market capitalization. We hope to be the first roasters in Europe to have the pleasure of selling 2015/2016 harvests. They will be sublime.</p>
      </div>
      <div class="col-md-6">
        <%= image_tag 'jamison.jpg', :class => "img-responsive img-border-left" %><br><br>
        <%= image_tag 'uniforme.jpg', :class => "img-responsive img-border-left" %>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
   <hr>
  <div class="row text-center">
    <div class="box">
      <div class="col-lg-12" id="call_to_action">
        <h2><a href="/shop">COME AND <strong>VISIT OUR STORE</strong>. IT'S FULL OF DELICIOUS COFFEE!</a></h2>
      </div>
    </div>
  </div>
  <hr>
</div>

app/views/coffees/finca_fernandez.html.erb
<div class="container coffee-profile-section">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <h2 class="intro-text text-center">ELIDA ESTATES</h2>
        <hr>
      </div>
      <div class="col-md-6">
        <p>Our founder, Juan Francisco Pardini, was born and raised in Panama. He developed an obsession with coffee from an early age, as it was the smell of wet coffee fields that kept bringing him back to the legendary area of Boquete every year. With a dream in mind he seeked the caffeine visionaries of this Century. From Stockholm to NYC to London to Paris. He learned roasting, espresso and farm production. When he got tired of jumping around, he created this company as a think tank to concentrate on the research and the craft of harnessing the rarest and finest coffees in Panama.</p>
      </div>
      <div class="col-md-6">
        <img class="img-responsive img-border-left" src="/assets/roasting.jpg" alt="">
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
   <hr>
  <div class="row text-center">
    <div class="box">
      <div class="col-lg-12" id="call_to_action">
        <h2><a href="/shop">COME AND <strong>VISIT OUR STORE</strong>. IT'S FULL OF DELICIOUS COFFEE!</a></h2>
      </div>
    </div>
  </div>
  <hr>
</div>

app/views/coffees/finca_jaramillo.html.erb
<div class="container coffee-profile-section">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <h2 class="intro-text text-center">FINCA JARAMILLO</h2>
        <hr>
      </div>
      <div class="col-md-6">
        <p>Our founder, Juan Francisco Pardini, was born and raised in Panama. He developed an obsession with coffee from an early age, as it was the smell of wet coffee fields that kept bringing him back to the legendary area of Boquete every year. With a dream in mind he seeked the caffeine visionaries of this Century. From Stockholm to NYC to London to Paris. He learned roasting, espresso and farm production. When he got tired of jumping around, he created this company as a think tank to concentrate on the research and the craft of harnessing the rarest and finest coffees in Panama.</p>
      </div>
      <div class="col-md-6">
        <img class="img-responsive img-border-left" src="/assets/roasting.jpg" alt="">
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
   <hr>
  <div class="row text-center">
    <div class="box">
      <div class="col-lg-12" id="call_to_action">
        <h2><a href="/shop">COME AND <strong>VISIT OUR STORE</strong>. IT'S FULL OF DELICIOUS COFFEE!</a></h2>
      </div>
    </div>
  </div>
  <hr>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <p><a href="http://facebook.com/pardinicoffeecompany"><i class="fa fa-facebook fa-3x" style="padding:2em;"></i></a><a href="http://twitter.com/pardinicoffee"><i class="fa fa-twitter fa-3x" style="padding:2em;"></i></a><a href="mailto:pardinicoffee@gmail.com?Subject=I%20want%20coffee"><i class="fa fa-envelope fa-3x" style="padding:2em;"></i></a></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="nav_link"><a href="/about">ABOUT</a></li>
      <li class="nav_link"><a href="/coffee">COFFEE</a></li>
      <li><a href="/"><%= image_tag 'pardini_logo.png', :class => "logo-hide" %></a></li>
      <li class="nav_link"><a href="/shop">SHOP</a></li>
      <li class="nav_link"><a href="/blog">BLOG</a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_purchase_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">COFFEE AFICIONADO</h4>
      </div>
      <div class="modal-body">
        <p>We are very proud to be your coffee roaster. Due to an unexpected increase in the demand for our coffee, we are creating a funky subscription-based platform for our clients to tailor the perfect coffee experience. As such, we are currently taking orders only by email.</p>

        <p>Placing your order now guarantees that you can start enjoying your coffee at the earliest opportunity. Please leave your details and we will make sure to deliver a delicious bag of coffee to your door.</p>  
      </div>
      <%= render partial: "admin/clients/form" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pardini Coffee Co. | Coffee Microroasters" %></title>
    <link rel="shortcut icon" href="http://www.otokostore.co/uploads/post/images/classic-fedora-panama-hat.png" type="image/png"/>
    <meta name="description" content="Pardini Coffee Co. | Microroaster in Paris">
    <meta name="Juan Francisco Pardini" content="Pardini Coffee Company">
    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true  %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true  %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.9.2/jquery-ui.js"></script> 
    <script src="https://code.jquery.com/jquery-migrate-1.2.1.js"></script>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render partial: "layouts/navigation" %>
    <%= yield %> 
    <%= render partial: "layouts/footer" %>     
  </body>
</html>

app/views/posts/panama_coffeeshops.html.erb
<div class="container blog-post-section">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <h2 class="intro-text text-center">Panama's first coffeeshops</strong></h2>
        <hr>
      </div>
      <div class="col-md-12">
        <p>For a while the idea was a bit ironic. A country producing the best plants in the world…with no coffeeshops in town to taste them. And you know what I mean by coffeeshops. It was inconceivable. Just imagine a place near the Equator with elevation ranging from sea level to 3,400 meters and one of the richest volcanic soils this side of the planet has to offer. If Thomas More was a farmer instead of a trippy philosopher, he would have envisioned Utopia exactly as I just described Panama. So what would happen when you place the seeds of human’s most cherished addiction into that ground? Well you get Eden’s fruit…the coveted geisha. However, all that magical fruit was being picked and shipped to destinations far away. But that began to change a year ago when a few young entrepreneurs decided to take things into their hands.</p><br>
        <%= image_tag 'unido_cafe.jpg', :class => "img-responsive img-border-left" %><br>
        <p>A couple of Panamanian kids who had all studied in the U.S. and lived the amazing experiences that places like Portland and California have to offer, are now the pioneers of the coffeeshop scene in what the New York Times 2013 nominated as #1 destination. The place to be. These guys all came from different backgrounds, different trains of thought. But they all converged on the same idea. One came from a culinary, musical world. Another from a gourmet family with a financial eye. And the other had three generations of producers in his family. And these are just the first. They all started with the same idea: hunt the best varieties in the country and bring them to an acute-palate public. It didn’t matter if a guy from across the street or a girl who flew from Norway came to the counter, the product always had to be nothing short of incredible. It had to bring out the defining and hidden aspects of each zone, of each producer and mainly, of each plant.</p><br>
        <p>You do know what plant I am talking about right?</p><br>
        <%= image_tag 'selfie_farm.jpg', :class => "img-responsive img-border-left" %><br>
        <p>You guessed right. It’s coffee. While many of the people in Montevideo and Amsterdam must think I am joking, the fact is the best coffeeshops should be at source. At the origin. And that’s in Panama. Or Burundi. Or Tegucigalpa. It’s not fair that a small group of connoisseurs in each country is deprived of the finest fruits in their country because the only importers, roasters and shop owners that are showing the interest and meeting the price are those sitting thousands of kilometers away. I know of coffee from El Salvador’s volcanoes that only gets tasted by those who visit coffeeshops in London and green beans from Jamaica labored by its finest people that is not even owned by locals. The Panama boys have started to tip the balance. Places like Bajareque, Cafe Unido and TeCafe are roasting to the feeling of a hand chronometer and a trained set of senses. Their knowledge of the medium is unparalleled because they either learned it in the farm or they travelled far away to seek the wisest of teachers. At the core they all learned to roast. Then they setup an infrastructure adapted to the demand that they saw and that they searched for…whether it was a spot to park fixies and walk in fine denims or if it was a spot to tell tales and to feel like you’re worth the five stars.</p><br>
        <p>Even typographic design was an aspect that became of interest when setting up one of the trendiest business startups in the second decade of the 21st Century. You see the world right now is suffering from what I call the New World Industrial revolution. An era in which makers command the men with hats. Don’t believe me? Look at the coolest jobs of 2014: web developer, barista, 3D printer. In that same order. I am sorry but I do not see any investment bankers or NGO crusaders there (those were pretty cool 10 years ago). So I get back to the maker revolution. Coffee is a hand crafted a product as you can get. From picking the fruit from the tree to stamping the package with your Skandi styled, Helvetica Neue written logo. Look at TeCafe’s menu or information cards. Admire Cafe Unido’s logo.</p><br>
        <%= image_tag 'te_cafe.jpg', :class => "img-responsive img-border-left" %><br>
        <p>It’s quite funny that what began as a geeky, underground thing…something that was in the same level as Call of Duty and joints, suddenly caught on fire. But not like a space rocket. More like a tumbleweed that has gradually began to roll…always keeping a stable momentum that only solidifies more and more the third wave of coffee. A moment in time where human fuel has gone from a dark and strong label to a tangerines and mangos with a white chocolate aftertaste description. Panama has always taken a bit to look at trends or waves, assessing them and then deciding if to act or not, rather than just jumping on it. But we are now seeing an increase in trend adoption and in venture setups. In the future, this is what Panama’s coffeeshops dream of: to see their hand-crafted products sold and enjoyed abroad. Only then will they be satisfied.</p><br>
        <p>Un fuerte saludo a Wilford, a Benito, a Mario y a Lucas!</p><br>
        <p>Keep roasting, keep enjoying it.</p>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="row">
    <div class="box">
      <div class="col-lg-12">
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="container about-section">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <h2 class="intro-text text-center">A long time ago in a galaxy <strong>FAR, FAR AWAY...</strong></h2>
        <hr>
      </div>
      <div class="col-md-6">
        <p>Our founder, Juan Francisco Pardini, was born and raised in Panama. He developed an obsession with coffee from an early age, as it was the smell of wet coffee fields that kept bringing him back to the legendary area of Boquete every year. With a dream in mind he seeked the caffeine visionaries of this Century. From Stockholm to NYC to London to Paris. He learned roasting, espresso and farm production. When he got tired of jumping around, he created this company as a think tank to concentrate on the research and the craft of harnessing the rarest and finest coffees in Panama.</p>
      </div>
      <div class="col-md-6">
        <%= image_tag 'roasting.jpg', :class => "img-responsive img-border-left" %>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
   <hr>
  <div class="row text-center">
    <div class="box">
      <div class="col-lg-12" id="call_to_action">
        <h2><a href="/shop">COME AND <strong>VISIT OUR STORE</strong>. IT'S FULL OF DELICIOUS COFFEE!</a></h2>
      </div>
    </div>
  </div>
  <hr>
</div>

app/views/welcome/blog.html.erb
<div class="container blog-section">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <h2 class="intro-text text-center">Let us <strong>SHARE</strong></h2>
        <hr>
      </div>
      <div class="col-md-12">
        <a href="/blog/panama_coffeeshops">Panama's first coffeeshops</a>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="row">
    <div class="box">
      <div class="col-lg-12">
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>